name: Maven Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        server-id: github           # matches your pom’s <distributionManagement><repository><id>
        settings-path: ~/.m2        # location for settings.xml

    - name: Configure Maven auth
      run: |
        mkdir -p ~/.m2
        cat > ~/.m2/settings.xml <<EOF
        <settings>
          <servers>
            <server>
              <id>private-repo</id>
              <username>${PRIVATE_REPO_USERNAME}</username>
              <password>${PRIVATE_REPO_TOKEN}</password>
            </server>
            <server>
              <id>github</id>
              <username>${GITHUB_ACTOR}</username>
              <password>${GITHUB_TOKEN}</password>
            </server>
          </servers>
        </settings>
        EOF
      env:
        PRIVATE_REPO_USERNAME: ${{ secrets.PRIVATE_REPO_USERNAME }}
        PRIVATE_REPO_TOKEN:      ${{ secrets.PRIVATE_REPO_TOKEN }}
        GITHUB_TOKEN:            ${{ github.token }}

    - name: Build with Maven
      run: mvn -U -B package --file pom.xml

    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy --file pom.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}
