name: Maven Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        settings-path: ~/.m2

    - name: Configure Maven auth
      run: |
        rm -rf ~/.m2/repository/com/libraries/auth
        mkdir -p ~/.m2
        cat > ~/.m2/settings.xml <<EOF
        <settings>
          <servers>
            <server>
              <id>private-repo</id>
              <username>${{ secrets.PRIVATE_REPO_USERNAME }}</username>
              <password>${{ secrets.PRIVATE_REPO_TOKEN }}</password>
            </server>
            <server>
              <id>github</id>
              <username>${{ github.actor }}</username>
              <password>${{ github.token }}</password>
            </server>
          </servers>
        </settings>
        EOF

    - name: Build with Maven (force updates)
      run: mvn -U -B clean package --file pom.xml

    - name: Publish to GitHub Packages
      run: mvn -U deploy --file pom.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}
