# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ~/.m2# location for the settings.xml file
    - name: Setup private libraries
    - name: Configure Maven auth
      run: |
        mkdir -p ~/.m2
        cat > ~/.m2/settings.xml <<EOF
        <settings>
          <servers>
            <server>
              <id>private-repo</id>
              <username>${PRIVATE_REPO_USERNAME}</username>
              <password>${PRIVATE_REPO_TOKEN}</password>
            </server>
            <server>
              <id>github</id>
              <username>${GITHUB_ACTOR}</username>
              <password>${GITHUB_TOKEN}</password>
            </server>
          </servers>
        </settings>
        EOF
      env:
        PRIVATE_REPO_USERNAME: ${{ secrets.PRIVATE_REPO_USERNAME }}
        PRIVATE_REPO_TOKEN:      ${{ secrets.PRIVATE_REPO_TOKEN }}
        GITHUB_TOKEN:            ${{ github.token }}

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}
